"""workspace lease purpose (human vs agent branch)

Revision ID: 16bd9e537d89
Revises: 458ad795a7ff
Create Date: 2026-07-23 13:52:32.619879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16bd9e537d89'
down_revision: Union[str, Sequence[str], None] = '458ad795a7ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspace_lease', sa.Column('purpose', sa.String(length=16), nullable=False, server_default=sa.text("'human'")))
    op.create_index(op.f('ix_workspace_lease_purpose'), 'workspace_lease', ['purpose'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspace_lease_purpose'), table_name='workspace_lease')
    op.drop_column('workspace_lease', 'purpose')
    # ### end Alembic commands ###
