"""initial schema

Revision ID: e926abd73c15
Revises: 
Create Date: 2026-07-21 11:06:46.603630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e926abd73c15'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotator',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annotator_email'), 'annotator', ['email'], unique=True)
    op.create_table('task',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=96), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=96), nullable=False),
    sa.Column('difficulty', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('start_url', sa.Text(), nullable=False),
    sa.Column('seed_state', sa.JSON(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_external_id'), 'task', ['external_id'], unique=True)
    op.create_index(op.f('ix_task_source'), 'task', ['source'], unique=False)
    op.create_table('review_session',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('annotator_id', sa.Uuid(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('agent', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('rerun_from', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['annotator_id'], ['annotator.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_session_annotator_id'), 'review_session', ['annotator_id'], unique=False)
    op.create_index(op.f('ix_review_session_status'), 'review_session', ['status'], unique=False)
    op.create_index(op.f('ix_review_session_task_id'), 'review_session', ['task_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['review_session.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_session_id'), 'audit_log', ['session_id'], unique=False)
    op.create_table('submission',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('reward', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('submitted_with_override', sa.Boolean(), nullable=False),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['review_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submission_session_id'), 'submission', ['session_id'], unique=False)
    op.create_table('trajectory',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('agent', sa.String(length=32), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['review_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trajectory_session_id'), 'trajectory', ['session_id'], unique=False)
    op.create_table('trajectory_branch',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('from_step', sa.Integer(), nullable=False),
    sa.Column('correction', sa.Text(), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['trajectory_branch.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['review_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trajectory_branch_parent_id'), 'trajectory_branch', ['parent_id'], unique=False)
    op.create_index(op.f('ix_trajectory_branch_session_id'), 'trajectory_branch', ['session_id'], unique=False)
    op.create_table('verifier_suite',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['review_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verifier_suite_session_id'), 'verifier_suite', ['session_id'], unique=False)
    op.create_table('benchmark_run',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('suite_id', sa.Uuid(), nullable=False),
    sa.Column('reward', sa.Integer(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['suite_id'], ['verifier_suite.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_benchmark_run_suite_id'), 'benchmark_run', ['suite_id'], unique=False)
    op.create_table('trajectory_step',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trajectory_id', sa.Uuid(), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tab_id', sa.String(length=32), nullable=False),
    sa.Column('screenshot_url', sa.Text(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('url_after', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['trajectory_id'], ['trajectory.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trajectory_step_trajectory_id'), 'trajectory_step', ['trajectory_id'], unique=False)
    op.create_table('verifier',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('suite_id', sa.Uuid(), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('assertion', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('check_ir', sa.JSON(), nullable=False),
    sa.Column('gym_result', sa.String(length=8), nullable=False),
    sa.Column('fails_until_corrected', sa.Boolean(), nullable=False),
    sa.Column('placeholder', sa.Boolean(), nullable=False),
    sa.Column('added_by_human', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['suite_id'], ['verifier_suite.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verifier_suite_id'), 'verifier', ['suite_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verifier_suite_id'), table_name='verifier')
    op.drop_table('verifier')
    op.drop_index(op.f('ix_trajectory_step_trajectory_id'), table_name='trajectory_step')
    op.drop_table('trajectory_step')
    op.drop_index(op.f('ix_benchmark_run_suite_id'), table_name='benchmark_run')
    op.drop_table('benchmark_run')
    op.drop_index(op.f('ix_verifier_suite_session_id'), table_name='verifier_suite')
    op.drop_table('verifier_suite')
    op.drop_index(op.f('ix_trajectory_branch_session_id'), table_name='trajectory_branch')
    op.drop_index(op.f('ix_trajectory_branch_parent_id'), table_name='trajectory_branch')
    op.drop_table('trajectory_branch')
    op.drop_index(op.f('ix_trajectory_session_id'), table_name='trajectory')
    op.drop_table('trajectory')
    op.drop_index(op.f('ix_submission_session_id'), table_name='submission')
    op.drop_table('submission')
    op.drop_index(op.f('ix_audit_log_session_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_review_session_task_id'), table_name='review_session')
    op.drop_index(op.f('ix_review_session_status'), table_name='review_session')
    op.drop_index(op.f('ix_review_session_annotator_id'), table_name='review_session')
    op.drop_table('review_session')
    op.drop_index(op.f('ix_task_source'), table_name='task')
    op.drop_index(op.f('ix_task_external_id'), table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_annotator_email'), table_name='annotator')
    op.drop_table('annotator')
    # ### end Alembic commands ###
